apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: app-monitor-daemonset 
spec:
  selector:
    matchLabels:
      name: app-monitor-daemonset
  template:
    metadata:
      labels:
        name: app-monitor-daemonset
    spec:
      nodeSelector:
        env: dev 
      containers:
        - name: app-monitor-daemonset 
          image: vikramnagarkar/app-monitor-daemonset
